### PR TITLE
AMBIT database data

### PR DESCRIPTION
**Pull request by jmillanacosta**
Solves #18 

Added [script](https://github.com/NanoCommons/erm-database/blob/adds-ambit/ambit_databases.js) to retrieve AMBIT database info, updated and new ERM data files, a new 'databases' data source and a database list for the substances page.

For now the list in the `substance` layout displays only the database name, but if we add a link field to each database file in  `_data/databases/` we can update the list with a href
```
{% if databases.size > 0 %}
  <h2 class="tag-title">Databases</h2>
  <ul>
    {% for database in databases %}
      {% for site_database_hash in site.data.databases %}
        {% assign site_database = site_database_hash[1] %}
        {% if database == site_database.title %}
          <li>{{ database }}</li>
        {% endif %}
      {% endfor %}      
    {% endfor %}
  </ul>
{% endif %}
```

image

### CODE REVIEW

**Comment by egonw** [comment]
Almost looks good. You remove the dataset items, which we will want to keep too. Datasets are things deposited on Zenodo, with a DOI, and the databases like things like AMBIT. I'll merge and we'll go from there. Thanks!!!!

**Comment by egonw** [comment]
Example uses of `dataset` are for example:

image

**Comment by jmillanacosta** [comment]
@egonw I see the confusion now, good thing you spotted this

**Comment by egonw** [comment]
That's what the peer review is about :)

**Pull request merged**
